# Generated by Django 3.1.7 on 2021-02-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('BirthDate', models.DateField()),
                ('Plate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=50)),
                ('Plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_app.user')),
            ],
        ),
    ]
