# Generated by Django 3.1.7 on 2021-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Plate',
            field=models.CharField(max_length=20),
        ),
    ]
